name: Build and publish manually
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Build image 
        run: sudo ./mre build
      - name: Install doctl 
        uses: digitalocean/action-doctl@v2
        env:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        with:
          token: '58a6a72a5dd977db4b128484a0b9848f58538848c3e64ae3873afb8801aeb7ea'
      - name: Log in to DO Container Registry 
        run: doctl registry login --expiry-seconds 600
      - name: Tag image 
        run:
          docker tag mre/frontend registry.digitalocean.com/microrealestate-vi/mre:${{github.event.inputs.version }}
      - name: Push image to DO Container Registry 
        run: docker push registry.digitalocean.com/microrealestate-vi/mre:${{ github.event.inputs.version }}
